### ISSUE TITLE
Second "Sign in with email" button on page doesnt work

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tincan#15]
http://tincan.im/

The first sign in button at the top of the page seems to work fine.
The second sign in button at the bottom of the page doesnt seem to do anything.

Not sure if it is due to the fact both buttons seem to share the same ID and therefore the onclick() handler is only applied to the first matching DOM element.

**Comment by ryanseys** [comment]
Nice catch... Thanks! Will fix!

**Comment by ryanseys** [comment]
Removed the button while we are in an experimental state, this will ensure users see the experimental warning near the top button.
