### ISSUE TITLE
Chrome reports a 404 when loading tincan.im (source map)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tincan#16]
**Steps to reproduce:**
1. Go to http://tincan.im/ in Google Chrome

**Actual results:**
The Chrome Dev Tools report the following 404 error:

> GET http://tincan.im/lib/jquery-1.10.1.min.map 404 (Not Found)

And sure enough the file isn't there.

If you load the same page in FF24, I see the following message in the console:

> [15:52:06.802] SyntaxError: Using //@ to indicate source map URL pragmas is deprecated. Use //# instead @ http://tincan.im/lib/jquery.min.js:1

Looking at the jquery.min.js file header, it looks like the culprit is this:

```
/*! jQuery v1.10.1 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
//@ sourceMappingURL=jquery-1.10.1.min.map
*/
```

I believe we can just grab the source map files from the jQuery CDN at http://code.jquery.com/jquery-1.10.1.min.map and put it beside the minified /lib/jquery.min.js file.

More details at http://blog.jquery.com/2013/01/09/jquery-1-9-rc1-and-migrate-rc1-released/#sourcemaps and more details on the //# vs //@ syntax at https://hacks.mozilla.org/2013/05/compiling-to-javascript-and-debugging-with-source-maps/ (although it looks like that warning may be coming directly from the jQuery minified files, but we should be able to change that locally since we arent using an official jQuery CDN).

**Comment by ryanseys** [comment]
Will look into this.

**Comment by ryanseys** [comment]
Fixed.
