### ISSUE TITLE
app.js reports JSHint errors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tincan#17]
Errors:
1) Line 5: `store = new express.session.MemoryStore;`

> Missing '()' invoking a constructor.

2)  Line 60: `if (x==c_var) {`

> Expected '===' and instead saw '=='.

3) Line 61: `return unescape(y);`

> 'unescape' is not defined.

4)  Line 42: `function send_to_socket(id, args) {`

> 'send_to_socket' is defined but never used.

---

Of these, it looks like (3) may be the only borderline concerning one. According to MDN, it looks like `escape()` and `unescape()` are deprecated:

> The escape and unescape functions do not work properly for non-ASCII characters and have been deprecated. In JavaScript 1.5 and later, use `encodeURI()`, `decodeURI()`, `encodeURIComponent()`, and `decodeURIComponent()`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#escape_and_unescape_functions%28Obsoleted_above_JavaScript_1.5%29

**Comment by ryanseys** [comment]
Fixed.
