### ISSUE TITLE
tincan.im site should link to the official Mozilla GitHub repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tincan#18]
The http://tincan.im/ site should link to the Tin Can GitHub repo page (https://github.com/mozilla/tincan).

We should probably either do a "Fork me on GitHub" style banner (a la http://personatestuser.org/) or else maybe just link the text saying "100% open source" to the GitHub repo so users can easily find the source code.

**Comment by ryanseys** [comment]
Added a link :+1:
