### ISSUE TITLE
Persona signin process seems broken

### ISSUE THREAD

**Issue by n1k0** [mozilla/tincan#22]
![capture decran 2013-08-29 a 17 33 44](https://f.cloud.github.com/assets/41547/1050845/bb475740-10c0-11e3-9387-61c057d9d92c.png)

Using my mozilla.com email address. Latest nightly.

**Comment by ryanseys** [comment]
Hi Nick! Please note we are not using `login.persona.org` but instead a testing instance of Persona at `webrtc.personatest.org` which doesn't share the same database as the official persona server. What were your steps to reproduce this error?

**Comment by n1k0** [comment]
Just clicking the `Sign in with email` button and trying to enter my mozilla.com creds :)

I actually didn't notice the different server url, which is a shame ;) I'll be creating a new account there, you can safely close this one if you want.

**Comment by ryanseys** [comment]
Yes, sorry @mozilla.com email addresses will not work (in addition to gmail or yahoo) because these bridges are not available on this (very temporary, very ephemeral) Persona instance. I apologize that this is a current limitation of Tin Can.
