### ISSUE TITLE
Error on launch - clean install

### ISSUE THREAD

**Issue by andynicholson** [mozilla/tincan#23]
andy@erko:~/src/tincan$ npm start

> tincan@0.0.1 start /home/andy/src/tincan
> node app.js

   info  - socket.io started
Express server listening on port 3000 in development mode

/home/andy/src/tincan/node_modules/jade/node_modules/transformers/node_modules/uglify-js/lib/parse.js:53
KEYWORDS = makePredicate(KEYWORDS);
         ^
util.debug: Use console.error instead
DEBUG: ERROR in file: /home/andy/src/tincan/node_modules/jade/node_modules/transformers/node_modules/uglify-js/lib/parse.js / ReferenceError: KEYWORDS is not defined
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by ryanseys** [comment]
What version of `jade` are you using?

**Comment by ryanseys** [comment]
I just tried a clean install and could not reproduce.

Running `/path/to/tincan/node_modules/jade/bin/jade --version` produces `0.35.0`. What does it produce for you?

**Comment by andynicholson** [comment]
Strange, it doesnt work either

andy@erko:~/src/tincan$ ./node_modules/jade/bin/jade --version

/home/andy/src/tincan/node_modules/jade/node_modules/transformers/node_modules/uglify-js/lib/parse.js:53
KEYWORDS = makePredicate(KEYWORDS);
         ^
util.debug: Use console.error instead
DEBUG: ERROR in file: /home/andy/src/tincan/node_modules/jade/node_modules/transformers/node_modules/uglify-js/lib/parse.js / ReferenceError: KEYWORDS is not defined

**Comment by ryanseys** [comment]
Taking a look [here](https://github.com/visionmedia/jade/issues/1181) it recommends running `v0.10.17` of `node` or earlier. I am running `v0.10.12` and don't get the error. What version of `node` are you running?

**Comment by andynicholson** [comment]
andy@erko:~$ node --version
v0.11.7-pre

**Comment by andynicholson** [comment]
Oh sorry, I see you said "earlier" not "later" :) I will try that

**Comment by ryanseys** [comment]
Ah pre-release version of node would do it. Yes try downgrading :) I will
make this version constraint more clear in the documentation.

Thanks for reporting this bug!

**Comment by andynicholson** [comment]
v0.10.17 works

**Comment by goumoup** [comment]
Ei, I am having the same problem...
how do I install that version? 
I tried:
npm install node@0.10.17 but no luck..
: npm http 404 https://registry.npmjs.org/node/0.10.17

**Comment by pdehaan** [comment]
@pbodymind Does http://nodejs.org/dist/v0.10.17/ work? Or I think they just released 0.10.18 the other day...

**Comment by pdehaan** [comment]
@pbodymind I just installed TinCan on OSX 10.8.4 w/ Node.js 0.10.18 and it worked for me.
What OS/Node version are you using and what error/warning are you seeing?

**Comment by ryanseys** [comment]
I recommend using [nvm](https://github.com/creationix/nvm) to manage your versions of `node`

**Comment by Rkallenkoot** [comment]
I myself encountered the same issue, fixed it by installing a stable node version with [n](https://github.com/visionmedia/n). Usage of [n](https://github.com/visionmedia/n) is explained in detail, Good luck!
