### ISSUE TITLE
Add call notification sound

### ISSUE THREAD

**Issue by ryanseys** [mozilla/tincan#26]
Example: http://www.freesound.org/people/alienistcog/sounds/124716/

**Comment by ryanseys** [comment]
Looping now https://www.dropbox.com/s/rw57cjzklouse66/124716__alienistcog__tin-can-percussion.aiff?dl=0

Thanks @ryanfeeley !

**Comment by orafaelfragoso** [comment]
@ryanseys Dropbox link is broken

**Comment by ryanfeeley** [comment]
@rafaelfragosom Corrected the above link.

**Comment by orafaelfragoso** [comment]
@ryanfeeley Thanks!
