### ISSUE TITLE
Where can i find Persona IdP?

### ISSUE THREAD

**Issue by Pierpaolo1992** [mozilla/tincan#36]
Hi Ryan, i appreciate your project in WebRTC.
I'm working for my master thesis about performance analysis in two different streaming technologies, in the context of DRM: DASH and WebRTC.
From WebRTC-side, i have to use an identity provider. After a long searching, i've found your project: well, where could i found your IdP?

Thanks Ryan,
Best regards!

**Comment by shane-tomlinson** [comment]
Hi @Pierpaolo1992 - the Persona service (the IdP) shut down at the end of December 2016. The source code lives at https://github.com/mozilla/persona/, which means you are able to install and run your own local version.

**Comment by Pierpaolo1992** [comment]
Thanks, @shane-tomlinson . So do you think i could use this code for my personal webrtc idp provider?
